### ISSUE TITLE
quoting of invalidation args

### ISSUE THREAD

**Issue by automaticgiant** [vladcosorg/action-s3-cloudfront-smart-deploy#37]
i haven't dug in enough but i don't know that the exec/spawn call uses a shell, so when i do the invalidation with `*` in it, it complains. i think maybe you don't need to map/convert the paths to a quoted path, unless in some cases it would be running under a shell.

**Comment by automaticgiant** [comment]
colleague double checked me:

So, it uses @actions/exec,  https://github.com/actions/toolkit/blob/main/packages/exec/src/toolrunner.ts#L369 Is where spawn options are from
The async exec() function of ToolRunner in @actions/exec calls child_exec.[spawn()](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) with that and the getSpawnArgs as well https://github.com/actions/toolkit/blob/main/packages/exec/src/toolrunner.ts#L437
shell of options is defaulted to false:
shell [<boolean>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Boolean_type) | [<string>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) If true, runs command inside of a shell. Uses '/bin/sh' on Unix, and process.env.ComSpec on Windows. A different shell can be specified as a string. See [Shell requirements](https://nodejs.org/api/child_process.html#shell-requirements) and [Default Windows shell](https://nodejs.org/api/child_process.html#default-windows-shell).
Default: false (no shell).
It looks like they use it directly out of the box, the only place to add your own options is on the getExecOutput call
https://github.com/actions/toolkit/blob/main/packages/exec/src/exec.ts#L44
but they are not set, so no shell wrapper

**Comment by automaticgiant** [comment]
reproduced in a second use case by emptying bucket and redeploying
> /usr/local/bin/aws cloudfront create-invalidation --distribution-id EXM8UQJAEYXRO --paths "/*"

all that said, i like your action and want to keep using it

**Comment by automaticgiant** [comment]
it doesn't look like this case is covered, but i'm not sure if i'm missing something
https://github.com/vladcosorg/action-s3-cloudfront-smart-deploy/actions/runs/8969816907/job/24632013892

**Comment by EliveltonRepolho** [comment]
having same issue here it looks like:
```
/usr/local/bin/aws cloudfront create-invalidation --distribution-id E3K...QTU3F --paths /favicon.ico /index.html "/assets/*" "/demo/*" "/layout/*"
An error occurred (InvalidArgument) when calling the CreateInvalidation operation: Your request contains one or more invalid invalidation paths.
file:///home/runner/work/_actions/vladcosorg/action-s3-cloudfront-smart-deploy/v1/node_modules/@actions/exec/lib/toolrunner.js:592
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
^
Error: The process '/usr/local/bin/aws' failed with exit code 254
    at ExecState._setResult (file:///home/runner/work/_actions/vladcosorg/action-s3-cloudfront-smart-deploy/v1/node_modules/@actions/exec/lib/toolrunner.js:592:1)
    at ExecState.CheckComplete (file:///home/runner/work/_actions/vladcosorg/action-s3-cloudfront-smart-deploy/v1/node_modules/@actions/exec/lib/toolrunner.js:575:1)
    at ChildProcess.<anonymous> (file:///home/runner/work/_actions/vladcosorg/action-s3-cloudfront-smart-deploy/v1/node_modules/@actions/exec/lib/toolrunner.js:469:1)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1104:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Upload changes to S3 and issue Cloudfront invalidations
```
